//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        WindowsFormsApplication1.ServiceReference1.HelloWorldResponse HelloWorld(WindowsFormsApplication1.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.HelloWorldResponse> HelloWorldAsync(WindowsFormsApplication1.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/suma", ReplyAction="*")]
        double suma(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/suma", ReplyAction="*")]
        System.Threading.Tasks.Task<double> sumaAsync(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/resta", ReplyAction="*")]
        double resta(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/resta", ReplyAction="*")]
        System.Threading.Tasks.Task<double> restaAsync(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/multi", ReplyAction="*")]
        double multi(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/multi", ReplyAction="*")]
        System.Threading.Tasks.Task<double> multiAsync(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/divi", ReplyAction="*")]
        double divi(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/divi", ReplyAction="*")]
        System.Threading.Tasks.Task<double> diviAsync(double a, double b);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento operador del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RealizarOperacion", ReplyAction="*")]
        WindowsFormsApplication1.ServiceReference1.RealizarOperacionResponse RealizarOperacion(WindowsFormsApplication1.ServiceReference1.RealizarOperacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RealizarOperacion", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.RealizarOperacionResponse> RealizarOperacionAsync(WindowsFormsApplication1.ServiceReference1.RealizarOperacionRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento operador del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Precedencia", ReplyAction="*")]
        WindowsFormsApplication1.ServiceReference1.PrecedenciaResponse Precedencia(WindowsFormsApplication1.ServiceReference1.PrecedenciaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Precedencia", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.PrecedenciaResponse> PrecedenciaAsync(WindowsFormsApplication1.ServiceReference1.PrecedenciaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento token del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EsOperador", ReplyAction="*")]
        WindowsFormsApplication1.ServiceReference1.EsOperadorResponse EsOperador(WindowsFormsApplication1.ServiceReference1.EsOperadorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EsOperador", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.EsOperadorResponse> EsOperadorAsync(WindowsFormsApplication1.ServiceReference1.EsOperadorRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento postfijo del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EvaluarPostfijo", ReplyAction="*")]
        WindowsFormsApplication1.ServiceReference1.EvaluarPostfijoResponse EvaluarPostfijo(WindowsFormsApplication1.ServiceReference1.EvaluarPostfijoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EvaluarPostfijo", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.EvaluarPostfijoResponse> EvaluarPostfijoAsync(WindowsFormsApplication1.ServiceReference1.EvaluarPostfijoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento expresion del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConvertirAPostfijo", ReplyAction="*")]
        WindowsFormsApplication1.ServiceReference1.ConvertirAPostfijoResponse ConvertirAPostfijo(WindowsFormsApplication1.ServiceReference1.ConvertirAPostfijoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConvertirAPostfijo", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.ConvertirAPostfijoResponse> ConvertirAPostfijoAsync(WindowsFormsApplication1.ServiceReference1.ConvertirAPostfijoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplication1.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(WindowsFormsApplication1.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplication1.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(WindowsFormsApplication1.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RealizarOperacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RealizarOperacion", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplication1.ServiceReference1.RealizarOperacionRequestBody Body;
        
        public RealizarOperacionRequest() {
        }
        
        public RealizarOperacionRequest(WindowsFormsApplication1.ServiceReference1.RealizarOperacionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RealizarOperacionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double a;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double b;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string operador;
        
        public RealizarOperacionRequestBody() {
        }
        
        public RealizarOperacionRequestBody(double a, double b, string operador) {
            this.a = a;
            this.b = b;
            this.operador = operador;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RealizarOperacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RealizarOperacionResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplication1.ServiceReference1.RealizarOperacionResponseBody Body;
        
        public RealizarOperacionResponse() {
        }
        
        public RealizarOperacionResponse(WindowsFormsApplication1.ServiceReference1.RealizarOperacionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RealizarOperacionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double RealizarOperacionResult;
        
        public RealizarOperacionResponseBody() {
        }
        
        public RealizarOperacionResponseBody(double RealizarOperacionResult) {
            this.RealizarOperacionResult = RealizarOperacionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PrecedenciaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Precedencia", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplication1.ServiceReference1.PrecedenciaRequestBody Body;
        
        public PrecedenciaRequest() {
        }
        
        public PrecedenciaRequest(WindowsFormsApplication1.ServiceReference1.PrecedenciaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PrecedenciaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string operador;
        
        public PrecedenciaRequestBody() {
        }
        
        public PrecedenciaRequestBody(string operador) {
            this.operador = operador;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PrecedenciaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PrecedenciaResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplication1.ServiceReference1.PrecedenciaResponseBody Body;
        
        public PrecedenciaResponse() {
        }
        
        public PrecedenciaResponse(WindowsFormsApplication1.ServiceReference1.PrecedenciaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PrecedenciaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int PrecedenciaResult;
        
        public PrecedenciaResponseBody() {
        }
        
        public PrecedenciaResponseBody(int PrecedenciaResult) {
            this.PrecedenciaResult = PrecedenciaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EsOperadorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EsOperador", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplication1.ServiceReference1.EsOperadorRequestBody Body;
        
        public EsOperadorRequest() {
        }
        
        public EsOperadorRequest(WindowsFormsApplication1.ServiceReference1.EsOperadorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EsOperadorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string token;
        
        public EsOperadorRequestBody() {
        }
        
        public EsOperadorRequestBody(string token) {
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EsOperadorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EsOperadorResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplication1.ServiceReference1.EsOperadorResponseBody Body;
        
        public EsOperadorResponse() {
        }
        
        public EsOperadorResponse(WindowsFormsApplication1.ServiceReference1.EsOperadorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EsOperadorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool EsOperadorResult;
        
        public EsOperadorResponseBody() {
        }
        
        public EsOperadorResponseBody(bool EsOperadorResult) {
            this.EsOperadorResult = EsOperadorResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EvaluarPostfijoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EvaluarPostfijo", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplication1.ServiceReference1.EvaluarPostfijoRequestBody Body;
        
        public EvaluarPostfijoRequest() {
        }
        
        public EvaluarPostfijoRequest(WindowsFormsApplication1.ServiceReference1.EvaluarPostfijoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EvaluarPostfijoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsFormsApplication1.ServiceReference1.ArrayOfString postfijo;
        
        public EvaluarPostfijoRequestBody() {
        }
        
        public EvaluarPostfijoRequestBody(WindowsFormsApplication1.ServiceReference1.ArrayOfString postfijo) {
            this.postfijo = postfijo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EvaluarPostfijoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EvaluarPostfijoResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplication1.ServiceReference1.EvaluarPostfijoResponseBody Body;
        
        public EvaluarPostfijoResponse() {
        }
        
        public EvaluarPostfijoResponse(WindowsFormsApplication1.ServiceReference1.EvaluarPostfijoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EvaluarPostfijoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double EvaluarPostfijoResult;
        
        public EvaluarPostfijoResponseBody() {
        }
        
        public EvaluarPostfijoResponseBody(double EvaluarPostfijoResult) {
            this.EvaluarPostfijoResult = EvaluarPostfijoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConvertirAPostfijoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConvertirAPostfijo", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplication1.ServiceReference1.ConvertirAPostfijoRequestBody Body;
        
        public ConvertirAPostfijoRequest() {
        }
        
        public ConvertirAPostfijoRequest(WindowsFormsApplication1.ServiceReference1.ConvertirAPostfijoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConvertirAPostfijoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string expresion;
        
        public ConvertirAPostfijoRequestBody() {
        }
        
        public ConvertirAPostfijoRequestBody(string expresion) {
            this.expresion = expresion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConvertirAPostfijoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConvertirAPostfijoResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplication1.ServiceReference1.ConvertirAPostfijoResponseBody Body;
        
        public ConvertirAPostfijoResponse() {
        }
        
        public ConvertirAPostfijoResponse(WindowsFormsApplication1.ServiceReference1.ConvertirAPostfijoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConvertirAPostfijoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsFormsApplication1.ServiceReference1.ArrayOfString ConvertirAPostfijoResult;
        
        public ConvertirAPostfijoResponseBody() {
        }
        
        public ConvertirAPostfijoResponseBody(WindowsFormsApplication1.ServiceReference1.ArrayOfString ConvertirAPostfijoResult) {
            this.ConvertirAPostfijoResult = ConvertirAPostfijoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : WindowsFormsApplication1.ServiceReference1.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<WindowsFormsApplication1.ServiceReference1.WebServiceSoap>, WindowsFormsApplication1.ServiceReference1.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplication1.ServiceReference1.HelloWorldResponse WindowsFormsApplication1.ServiceReference1.WebServiceSoap.HelloWorld(WindowsFormsApplication1.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            WindowsFormsApplication1.ServiceReference1.HelloWorldRequest inValue = new WindowsFormsApplication1.ServiceReference1.HelloWorldRequest();
            inValue.Body = new WindowsFormsApplication1.ServiceReference1.HelloWorldRequestBody();
            WindowsFormsApplication1.ServiceReference1.HelloWorldResponse retVal = ((WindowsFormsApplication1.ServiceReference1.WebServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.HelloWorldResponse> WindowsFormsApplication1.ServiceReference1.WebServiceSoap.HelloWorldAsync(WindowsFormsApplication1.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            WindowsFormsApplication1.ServiceReference1.HelloWorldRequest inValue = new WindowsFormsApplication1.ServiceReference1.HelloWorldRequest();
            inValue.Body = new WindowsFormsApplication1.ServiceReference1.HelloWorldRequestBody();
            return ((WindowsFormsApplication1.ServiceReference1.WebServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        public double suma(double a, double b) {
            return base.Channel.suma(a, b);
        }
        
        public System.Threading.Tasks.Task<double> sumaAsync(double a, double b) {
            return base.Channel.sumaAsync(a, b);
        }
        
        public double resta(double a, double b) {
            return base.Channel.resta(a, b);
        }
        
        public System.Threading.Tasks.Task<double> restaAsync(double a, double b) {
            return base.Channel.restaAsync(a, b);
        }
        
        public double multi(double a, double b) {
            return base.Channel.multi(a, b);
        }
        
        public System.Threading.Tasks.Task<double> multiAsync(double a, double b) {
            return base.Channel.multiAsync(a, b);
        }
        
        public double divi(double a, double b) {
            return base.Channel.divi(a, b);
        }
        
        public System.Threading.Tasks.Task<double> diviAsync(double a, double b) {
            return base.Channel.diviAsync(a, b);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplication1.ServiceReference1.RealizarOperacionResponse WindowsFormsApplication1.ServiceReference1.WebServiceSoap.RealizarOperacion(WindowsFormsApplication1.ServiceReference1.RealizarOperacionRequest request) {
            return base.Channel.RealizarOperacion(request);
        }
        
        public double RealizarOperacion(double a, double b, string operador) {
            WindowsFormsApplication1.ServiceReference1.RealizarOperacionRequest inValue = new WindowsFormsApplication1.ServiceReference1.RealizarOperacionRequest();
            inValue.Body = new WindowsFormsApplication1.ServiceReference1.RealizarOperacionRequestBody();
            inValue.Body.a = a;
            inValue.Body.b = b;
            inValue.Body.operador = operador;
            WindowsFormsApplication1.ServiceReference1.RealizarOperacionResponse retVal = ((WindowsFormsApplication1.ServiceReference1.WebServiceSoap)(this)).RealizarOperacion(inValue);
            return retVal.Body.RealizarOperacionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.RealizarOperacionResponse> WindowsFormsApplication1.ServiceReference1.WebServiceSoap.RealizarOperacionAsync(WindowsFormsApplication1.ServiceReference1.RealizarOperacionRequest request) {
            return base.Channel.RealizarOperacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.RealizarOperacionResponse> RealizarOperacionAsync(double a, double b, string operador) {
            WindowsFormsApplication1.ServiceReference1.RealizarOperacionRequest inValue = new WindowsFormsApplication1.ServiceReference1.RealizarOperacionRequest();
            inValue.Body = new WindowsFormsApplication1.ServiceReference1.RealizarOperacionRequestBody();
            inValue.Body.a = a;
            inValue.Body.b = b;
            inValue.Body.operador = operador;
            return ((WindowsFormsApplication1.ServiceReference1.WebServiceSoap)(this)).RealizarOperacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplication1.ServiceReference1.PrecedenciaResponse WindowsFormsApplication1.ServiceReference1.WebServiceSoap.Precedencia(WindowsFormsApplication1.ServiceReference1.PrecedenciaRequest request) {
            return base.Channel.Precedencia(request);
        }
        
        public int Precedencia(string operador) {
            WindowsFormsApplication1.ServiceReference1.PrecedenciaRequest inValue = new WindowsFormsApplication1.ServiceReference1.PrecedenciaRequest();
            inValue.Body = new WindowsFormsApplication1.ServiceReference1.PrecedenciaRequestBody();
            inValue.Body.operador = operador;
            WindowsFormsApplication1.ServiceReference1.PrecedenciaResponse retVal = ((WindowsFormsApplication1.ServiceReference1.WebServiceSoap)(this)).Precedencia(inValue);
            return retVal.Body.PrecedenciaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.PrecedenciaResponse> WindowsFormsApplication1.ServiceReference1.WebServiceSoap.PrecedenciaAsync(WindowsFormsApplication1.ServiceReference1.PrecedenciaRequest request) {
            return base.Channel.PrecedenciaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.PrecedenciaResponse> PrecedenciaAsync(string operador) {
            WindowsFormsApplication1.ServiceReference1.PrecedenciaRequest inValue = new WindowsFormsApplication1.ServiceReference1.PrecedenciaRequest();
            inValue.Body = new WindowsFormsApplication1.ServiceReference1.PrecedenciaRequestBody();
            inValue.Body.operador = operador;
            return ((WindowsFormsApplication1.ServiceReference1.WebServiceSoap)(this)).PrecedenciaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplication1.ServiceReference1.EsOperadorResponse WindowsFormsApplication1.ServiceReference1.WebServiceSoap.EsOperador(WindowsFormsApplication1.ServiceReference1.EsOperadorRequest request) {
            return base.Channel.EsOperador(request);
        }
        
        public bool EsOperador(string token) {
            WindowsFormsApplication1.ServiceReference1.EsOperadorRequest inValue = new WindowsFormsApplication1.ServiceReference1.EsOperadorRequest();
            inValue.Body = new WindowsFormsApplication1.ServiceReference1.EsOperadorRequestBody();
            inValue.Body.token = token;
            WindowsFormsApplication1.ServiceReference1.EsOperadorResponse retVal = ((WindowsFormsApplication1.ServiceReference1.WebServiceSoap)(this)).EsOperador(inValue);
            return retVal.Body.EsOperadorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.EsOperadorResponse> WindowsFormsApplication1.ServiceReference1.WebServiceSoap.EsOperadorAsync(WindowsFormsApplication1.ServiceReference1.EsOperadorRequest request) {
            return base.Channel.EsOperadorAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.EsOperadorResponse> EsOperadorAsync(string token) {
            WindowsFormsApplication1.ServiceReference1.EsOperadorRequest inValue = new WindowsFormsApplication1.ServiceReference1.EsOperadorRequest();
            inValue.Body = new WindowsFormsApplication1.ServiceReference1.EsOperadorRequestBody();
            inValue.Body.token = token;
            return ((WindowsFormsApplication1.ServiceReference1.WebServiceSoap)(this)).EsOperadorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplication1.ServiceReference1.EvaluarPostfijoResponse WindowsFormsApplication1.ServiceReference1.WebServiceSoap.EvaluarPostfijo(WindowsFormsApplication1.ServiceReference1.EvaluarPostfijoRequest request) {
            return base.Channel.EvaluarPostfijo(request);
        }
        
        public double EvaluarPostfijo(WindowsFormsApplication1.ServiceReference1.ArrayOfString postfijo) {
            WindowsFormsApplication1.ServiceReference1.EvaluarPostfijoRequest inValue = new WindowsFormsApplication1.ServiceReference1.EvaluarPostfijoRequest();
            inValue.Body = new WindowsFormsApplication1.ServiceReference1.EvaluarPostfijoRequestBody();
            inValue.Body.postfijo = postfijo;
            WindowsFormsApplication1.ServiceReference1.EvaluarPostfijoResponse retVal = ((WindowsFormsApplication1.ServiceReference1.WebServiceSoap)(this)).EvaluarPostfijo(inValue);
            return retVal.Body.EvaluarPostfijoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.EvaluarPostfijoResponse> WindowsFormsApplication1.ServiceReference1.WebServiceSoap.EvaluarPostfijoAsync(WindowsFormsApplication1.ServiceReference1.EvaluarPostfijoRequest request) {
            return base.Channel.EvaluarPostfijoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.EvaluarPostfijoResponse> EvaluarPostfijoAsync(WindowsFormsApplication1.ServiceReference1.ArrayOfString postfijo) {
            WindowsFormsApplication1.ServiceReference1.EvaluarPostfijoRequest inValue = new WindowsFormsApplication1.ServiceReference1.EvaluarPostfijoRequest();
            inValue.Body = new WindowsFormsApplication1.ServiceReference1.EvaluarPostfijoRequestBody();
            inValue.Body.postfijo = postfijo;
            return ((WindowsFormsApplication1.ServiceReference1.WebServiceSoap)(this)).EvaluarPostfijoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplication1.ServiceReference1.ConvertirAPostfijoResponse WindowsFormsApplication1.ServiceReference1.WebServiceSoap.ConvertirAPostfijo(WindowsFormsApplication1.ServiceReference1.ConvertirAPostfijoRequest request) {
            return base.Channel.ConvertirAPostfijo(request);
        }
        
        public WindowsFormsApplication1.ServiceReference1.ArrayOfString ConvertirAPostfijo(string expresion) {
            WindowsFormsApplication1.ServiceReference1.ConvertirAPostfijoRequest inValue = new WindowsFormsApplication1.ServiceReference1.ConvertirAPostfijoRequest();
            inValue.Body = new WindowsFormsApplication1.ServiceReference1.ConvertirAPostfijoRequestBody();
            inValue.Body.expresion = expresion;
            WindowsFormsApplication1.ServiceReference1.ConvertirAPostfijoResponse retVal = ((WindowsFormsApplication1.ServiceReference1.WebServiceSoap)(this)).ConvertirAPostfijo(inValue);
            return retVal.Body.ConvertirAPostfijoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.ConvertirAPostfijoResponse> WindowsFormsApplication1.ServiceReference1.WebServiceSoap.ConvertirAPostfijoAsync(WindowsFormsApplication1.ServiceReference1.ConvertirAPostfijoRequest request) {
            return base.Channel.ConvertirAPostfijoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.ConvertirAPostfijoResponse> ConvertirAPostfijoAsync(string expresion) {
            WindowsFormsApplication1.ServiceReference1.ConvertirAPostfijoRequest inValue = new WindowsFormsApplication1.ServiceReference1.ConvertirAPostfijoRequest();
            inValue.Body = new WindowsFormsApplication1.ServiceReference1.ConvertirAPostfijoRequestBody();
            inValue.Body.expresion = expresion;
            return ((WindowsFormsApplication1.ServiceReference1.WebServiceSoap)(this)).ConvertirAPostfijoAsync(inValue);
        }
    }
}
